'use client';
import type {AuthUser,LocalPrinterSettings} from '@/types/pos';
import type {buildInvoiceDraft} from './invoice';
type Payload=ReturnType<typeof buildInvoiceDraft>;

export function receiptLines(payload:Payload,user:AuthUser,invoiceNo?:string){const h=payload.invoices;return [user.BranchName||'FUTEC',user.Address||'',`فاتورة رقم: ${invoiceNo||h.InvoiceNo}`,`الكاشير: ${user.Username}`,`التاريخ: ${new Date(h.RealTime).toLocaleString('ar-JO')}`,'--------------------------------',...payload.invoiceDtl.flatMap(x=>[`${x.Pro_AR_Name||x.Pro_EN_Name}  x${x.Qty}`,`${x.Price.toFixed(3)}        ${x.GrandTotal.toFixed(3)}`]),'--------------------------------',`المجموع: ${h.InvoiceSubTotal.toFixed(3)}`,`الخصم: ${h.InvoiceDiscountTotal.toFixed(3)}`,`الضريبة: ${h.InvoiceTaxTotal.toFixed(3)}`,`الإجمالي: ${h.InvoiceGrandTotal.toFixed(3)}`];}
export function kitchenLines(payload:Payload,items:Payload['invoiceDtl'],invoiceNo?:string,note=''){return [`طلب مطبخ #${invoiceNo||payload.invoices.InvoiceNo}`,`طاولة: ${payload.invoices.TableNo}`,'--------------------------------',...items.flatMap(x=>[`${x.Pro_AR_Name||x.Pro_EN_Name} × ${x.Qty}`,x.Flavors?`إضافات: ${x.Flavors}`:'']),note?`ملاحظة: ${note}`:''];}

export async function printReceipt(payload:Payload,user:AuthUser,settings:LocalPrinterSettings,invoiceNo?:string){return printLinesBySettings(receiptLines(payload,user,invoiceNo),settings,true);}
export async function printLinesBySettings(lines:string[],settings:LocalPrinterSettings,openCashDrawer=false){if(settings.printerType==='network'&&settings.printerCashIp){const data=await rasterEscPos(lines);await sendNetwork(settings.printerCashIp,settings.portCash,data,openCashDrawer);return;}if(settings.printerType==='usb'){await printUsb(await rasterEscPos(lines),openCashDrawer);return;}if(settings.printerType==='bluetooth'){await printBluetooth(await rasterEscPos(lines),openCashDrawer);return;}if(settings.printerType==='imin'){const w=window as unknown as {iminPrinter?:{printText?:(t:string)=>Promise<void>|void;openCashBox?:()=>Promise<void>|void}};if(w.iminPrinter?.printText){await w.iminPrinter.printText(lines.join('\n'));if(openCashDrawer)await w.iminPrinter.openCashBox?.();return;}}browserPrint(lines);}
export async function printKitchen(payload:Payload,settings:LocalPrinterSettings,note='',invoiceNo?:string){const configured=payload.invoiceDtl.map(item=>({item,printer:settings.categoryPrinterMap[String(item.CatID)]||0,prep:Number(item.PreparationTime)||0})).filter(x=>x.printer>0);if(!configured.length)return;const maxPrep=Math.max(...configured.map(x=>x.prep),0);const groups=new Map<string,Payload['invoiceDtl']>();for(const x of configured){const key=`${x.printer}_${x.prep}`;const a=groups.get(key)||[];a.push(x.item);groups.set(key,a);}for(const [key,items] of groups){const [pRaw,prepRaw]=key.split('_');const p=Number(pRaw),prep=Number(prepRaw);const ip=(settings as unknown as Record<string,string>)[`printerKitchenIp${p}`]||'';const port=(settings as unknown as Record<string,string>)[`portKitchen${p}`]||'9100';if(!ip||ip==='0')continue;const delay=Math.max(0,maxPrep-prep);const groupNote=delay>0?[note,`انتظار ${delay} د - ليجهز مع الطلب`].filter(Boolean).join(' · '):note;const run=()=>rasterEscPos(kitchenLines(payload,items,invoiceNo,groupNote)).then(data=>sendNetwork(ip,port,data,false)).catch(()=>{});if(delay>0)setTimeout(run,delay*60_000);else await run();}}
export async function openDrawer(settings:LocalPrinterSettings){if(settings.printerType==='network'&&settings.printerCashIp){await fetch('/api/print/network',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ip:settings.printerCashIp,port:Number(settings.portCash),lines:[],openDrawer:true})});}}
async function sendNetwork(ip:string,port:string,data:Uint8Array,drawer=false){const base64=bytesToBase64(drawer?concat(new Uint8Array([0x1b,0x70,0,0x19,0xfa]),data):data);const r=await fetch('/api/print/network',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ip,port:Number(port),dataBase64:base64})});if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error(x.message||'Printer error');}}
function browserPrint(lines:string[]){const w=window.open('','_blank','width=420,height=700');if(!w)return;w.document.write(`<html dir="rtl"><head><style>body{font-family:Tahoma,Arial;width:72mm;margin:auto;font-size:14px;white-space:pre-wrap;text-align:right}</style></head><body>${escape(lines.join('\n'))}<script>window.onload=()=>{window.print();window.close()}<\/script></body></html>`);w.document.close();}

async function printBluetooth(bytes:Uint8Array,drawer=false){
 const nav=navigator as unknown as {bluetooth?:{requestDevice:(o:{acceptAllDevices:boolean;optionalServices:(number|string)[]})=>Promise<any>}};
 if(!nav.bluetooth)throw new Error('Web Bluetooth غير مدعوم في هذا المتصفح');
 const device=await nav.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[0xff00,0xffe0,0xae30]});
 const server=await device.gatt?.connect(); if(!server)throw new Error('تعذر الاتصال بطابعة Bluetooth');
 const services=await server.getPrimaryServices(); let writable:any=null;
 for(const service of services){const chars=await service.getCharacteristics();writable=chars.find((c:any)=>c.properties?.writeWithoutResponse||c.properties?.write);if(writable)break;}
 if(!writable)throw new Error('لم يتم العثور على Bluetooth write characteristic');
 const data=drawer?concat(new Uint8Array([0x1b,0x70,0,0x19,0xfa]),bytes):bytes;
 for(let i=0;i<data.length;i+=180){const chunk=data.slice(i,i+180);if(writable.writeValueWithoutResponse)await writable.writeValueWithoutResponse(chunk);else await writable.writeValue(chunk);}
 try{device.gatt?.disconnect()}catch{}
}

async function printUsb(bytes:Uint8Array,drawer=false){const nav=navigator as unknown as {usb?:{requestDevice:(o:{filters:unknown[]})=>Promise<any>}};if(!nav.usb)throw new Error('WebUSB غير مدعوم في هذا المتصفح');const d=await nav.usb.requestDevice({filters:[]});await d.open();if(!d.configuration)await d.selectConfiguration(1);const iface=d.configuration.interfaces.find((i:any)=>i.alternates.some((a:any)=>a.endpoints.some((e:any)=>e.direction==='out')));if(!iface)throw new Error('تعذر إيجاد USB endpoint');await d.claimInterface(iface.interfaceNumber);const alt=iface.alternates.find((a:any)=>a.endpoints.some((e:any)=>e.direction==='out'));const ep=alt.endpoints.find((e:any)=>e.direction==='out');const data=drawer?concat(new Uint8Array([0x1b,0x70,0,0x19,0xfa]),bytes):bytes;await d.transferOut(ep.endpointNumber,data);await d.close();}
export async function rasterEscPos(lines:string[]):Promise<Uint8Array>{const width=576,pad=18,font=27,lineH=38;const canvas=document.createElement('canvas');const ctx=canvas.getContext('2d')!;ctx.font=`${font}px Tahoma, Arial`;const wrapped=lines.flatMap(line=>wrap(ctx,line,width-pad*2));canvas.width=width;canvas.height=Math.max(80,wrapped.length*lineH+24);const c=canvas.getContext('2d')!;c.fillStyle='white';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle='black';c.font=`${font}px Tahoma, Arial`;c.textAlign='right';c.direction='rtl';c.textBaseline='top';wrapped.forEach((line,i)=>c.fillText(line,width-pad,12+i*lineH));const img=c.getImageData(0,0,width,canvas.height);const bytesPerRow=Math.ceil(width/8);const raster=new Uint8Array(bytesPerRow*canvas.height);for(let y=0;y<canvas.height;y++){for(let x=0;x<width;x++){const i=(y*width+x)*4;const lum=(img.data[i]+img.data[i+1]+img.data[i+2])/3;if(lum<155)raster[y*bytesPerRow+(x>>3)]|=0x80>>(x&7);}}const header=new Uint8Array([0x1b,0x40,0x1d,0x76,0x30,0x00,bytesPerRow&255,(bytesPerRow>>8)&255,canvas.height&255,(canvas.height>>8)&255]);const cut=new Uint8Array([0x0a,0x0a,0x1d,0x56,0x41,0x03]);return concat(header,raster,cut);}
function wrap(ctx:CanvasRenderingContext2D,line:string,max:number){if(!line)return[''];const words=line.split(' '),out:string[]=[];let cur='';for(const word of words){const t=cur?`${cur} ${word}`:word;if(ctx.measureText(t).width>max&&cur){out.push(cur);cur=word;}else cur=t;}if(cur)out.push(cur);return out;}
function concat(...xs:Uint8Array[]){const n=xs.reduce((a,x)=>a+x.length,0),o=new Uint8Array(n);let p=0;xs.forEach(x=>{o.set(x,p);p+=x.length});return o;}function bytesToBase64(v:Uint8Array){let s='';for(let i=0;i<v.length;i+=0x8000)s+=String.fromCharCode(...v.subarray(i,i+0x8000));return btoa(s);}function escape(v:string){return v.replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]!));}
