'use client';
import React,{createContext,useCallback,useContext,useEffect,useMemo,useState} from 'react';
import type {AuthUser,CartItem,Category,Delivery,DeliveryDiscount,DeliverySelection,Discount,Flavor,LocalPrinterSettings,Offer,PaymentType,PendingOrder,Product,Question,RemoteSetting} from '@/types/pos';
import {loadUser} from '@/lib/session';
import {loadCatalog,getCash,getLastInvoice,getSaleDay,insertInvoice} from '@/lib/pos-api';
import {applyOffers,calculateCart} from '@/lib/pricing';
import {buildInvoiceDraft,getTaxOptions,rebasePendingInvoice,type PaymentMap} from '@/lib/invoice';
import {cacheCatalog,getCachedCatalog,getOrders,getPendingInvoices,savePendingInvoice,setOrders,setPendingInvoices} from '@/lib/offline';
import {loadLocalSettings,saveLocalSettings} from '@/lib/local-settings';
import {generateId} from '@/lib/generate-id';

type Catalog={categories:Category[];products:Product[];flavors:Flavor[];questions:Question[];offers:Offer[];discounts:Discount[];deliveries:Delivery[];deliveryDiscounts:DeliveryDiscount[];paymentTypes:PaymentType[];settings:RemoteSetting[];errors?:unknown[]};
interface PosCtx extends Catalog { user:AuthUser|null;loading:boolean;error:string;cart:CartItem[];orderType:number;discount:Discount|null;delivery:DeliverySelection|null;note:string;pendingOrders:PendingOrder[];printerSettings:LocalPrinterSettings;
 addProduct:(p:Product,opts?:{quantity?:number;flavors?:Flavor[];questions?:Product[];note?:string})=>void;updateQty:(id:string,q:number)=>void;removeItem:(id:string)=>void;clearCart:()=>void;setOrderType:(t:number)=>void;setDiscount:(d:Discount|null)=>void;setDelivery:(d:Delivery|null)=>void;setNote:(v:string)=>void;totals:ReturnType<typeof calculateCart>;refreshCatalog:()=>Promise<void>;holdOrder:(name?:string)=>Promise<void>;restoreOrder:(id:string)=>Promise<void>;deleteOrder:(id:string)=>Promise<void>;checkout:(payments:PaymentMap,isPrinted?:boolean)=>Promise<{invoiceNo:string;payload:ReturnType<typeof buildInvoiceDraft>;offline:boolean}>;syncPending:()=>Promise<number>;setPrinterSettings:(v:LocalPrinterSettings)=>void; }
const C=createContext<PosCtx|null>(null);
const empty:Catalog={categories:[],products:[],flavors:[],questions:[],offers:[],discounts:[],deliveries:[],deliveryDiscounts:[],paymentTypes:[],settings:[]};

export function PosProvider({children}:{children:React.ReactNode}){
 const [user,setUser]=useState<AuthUser|null>(null); const [catalog,setCatalog]=useState<Catalog>(empty); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const [cart,setCart]=useState<CartItem[]>([]); const [orderTypeState,setOrderTypeState]=useState(2); const [discount,setDiscountState]=useState<Discount|null>(null); const [delivery,setDeliveryState]=useState<DeliverySelection|null>(null); const [note,setNote]=useState(''); const [pendingOrders,setPendingOrdersState]=useState<PendingOrder[]>([]); const [printerSettings,setPrinterSettings]=useState<LocalPrinterSettings>(()=>loadLocalSettings());
 const refreshCatalog=useCallback(async()=>{ const u=loadUser(); if(!u)return; setLoading(true); try{ const data=await loadCatalog(u.DefaultBranch); setCatalog(data); await cacheCatalog(data); setError(data.errors?.length?'تم تحميل البيانات مع وجود بعض أخطاء المزامنة':''); }catch(e){ const cached=await getCachedCatalog<Catalog>(); if(cached)setCatalog(cached); setError(e instanceof Error?e.message:'فشل تحميل البيانات'); }finally{setLoading(false);} },[]);
 useEffect(()=>{ const u=loadUser(); setUser(u); Promise.all([getCachedCatalog<Catalog>(),getOrders()]).then(([cached,orders])=>{if(cached)setCatalog(cached);setPendingOrdersState(orders);}); if(u)refreshCatalog();else setLoading(false); },[refreshCatalog]);
 const setOrderType=(t:number)=>{setOrderTypeState(t);setCart(c=>applyOffers(c,t));};
 const addProduct=(p:Product,opts:{quantity?:number;flavors?:Flavor[];questions?:Product[];note?:string}={})=>setCart(c=>{ const quantity=opts.quantity||1,flavors=opts.flavors||[],questions=opts.questions||[]; const productOffers=[...catalog.offers.filter(o=>o.productId===p.proId),...catalog.offers.filter(o=>questions.some(q=>q.proId===o.productId))]; const same=c.find(i=>!i.isOffer&&i.product.proId===p.proId&&sameIds(i.flavors,flavors,'flavorNo')&&sameIds(i.questions,questions,'proId')); let next:CartItem[]; if(same)next=c.map(i=>i.id===same.id?{...i,quantity:i.quantity+quantity,note:opts.note??i.note}:i); else next=[...c,{id:generateId(),product:p,quantity,flavors,questions,offers:productOffers,note:opts.note||'',isOffer:false,extraItemId:null,originalPrice:p.price}]; return applyOffers(next,orderTypeState);});
 const updateQty=(id:string,q:number)=>setCart(c=>applyOffers(c.filter(i=>i.id!==id||q>0).map(i=>i.id===id?{...i,quantity:Math.max(0,q)}:i).filter(i=>i.quantity>0&&!i.isOffer),orderTypeState));
 const removeItem=(id:string)=>setCart(c=>applyOffers(c.filter(i=>i.id!==id&&!((i.isOffer&&i.extraItemId===id))),orderTypeState));
 const clearCart=()=>{setCart([]);setDiscountState(null);setDeliveryState(null);setNote('');};
 const setDelivery=(d:Delivery|null)=>{ if(!d){setDeliveryState(null);return;} const dd=catalog.deliveryDiscounts.find(x=>x.companyId===d.companyId)||null;setDeliveryState({delivery:d,discount:dd}); };
 const opts=getTaxOptions(catalog.settings); const totals=useMemo(()=>calculateCart(cart,{...opts,discount,delivery}),[cart,opts.taxPercentage,opts.priceIncludesTax,opts.taxIncludesDiscount,discount,delivery]);
 useEffect(()=>{ try{ const snapshot={items:cart.map(i=>({name:i.product.arName||i.product.enName,quantity:i.quantity,price:i.product.price})),...totals,branch:user?.BranchName||''}; localStorage.setItem('futec-pos-display',JSON.stringify(snapshot)); const bc=new BroadcastChannel('futec-pos-display'); bc.postMessage(snapshot); bc.close(); }catch{} },[cart,totals,user]);
 const holdOrder=async(name?:string)=>{ if(!cart.length)return; const order:PendingOrder={orderId:generateId(),orderDate:new Date().toISOString(),orderStatus:'pending',name,cartItems:cart,orderType:orderTypeState,discount,delivery,note}; const next=[...pendingOrders,order]; setPendingOrdersState(next);await setOrders(next);clearCart(); };
 const restoreOrder=async(id:string)=>{const o=pendingOrders.find(x=>x.orderId===id);if(!o)return;setCart(o.cartItems);setOrderTypeState(o.orderType);setDiscountState(o.discount||null);setDeliveryState(o.delivery||null);setNote(o.note||'');const next=pendingOrders.filter(x=>x.orderId!==id);setPendingOrdersState(next);await setOrders(next);};
 const deleteOrder=async(id:string)=>{const next=pendingOrders.filter(x=>x.orderId!==id);setPendingOrdersState(next);await setOrders(next);};
 const checkout=async(payments:PaymentMap,isPrinted=true)=>{if(!user)throw new Error('لا توجد جلسة مستخدم');if(!cart.length)throw new Error('السلة فارغة');let meta:Record<string,unknown>={};if(navigator.onLine){ try{const [sale,cash,last]=await Promise.all([getSaleDay(user.DefaultBranch),getCash(user.UserNo),getLastInvoice(user.DefaultBranch)]);meta={invoiceNo:last.InvoiceNo,queue:last.Queue,cashNo:cash.CashNo,salesDate:dateOnly(sale.LineDate)};}catch(e){throw e;} }
   const payload=buildInvoiceDraft({cart,user,settings:catalog.settings,payments,discount,delivery,isPrinted,meta,stationId:printerSettings.stationName});
   if(!navigator.onLine){await savePendingInvoice(payload);const no=String(payload.invoices.InvoiceNo);clearCart();return{invoiceNo:no,payload,offline:true};}
   try{const no=await insertInvoice(payload);clearCart();return{invoiceNo:String(no||payload.invoices.InvoiceNo),payload,offline:false};}catch(e){ if(!navigator.onLine){await savePendingInvoice(payload);clearCart();return{invoiceNo:String(payload.invoices.InvoiceNo),payload,offline:true};} throw e; }
 };
 const syncPending=useCallback(async()=>{const u=loadUser();if(!u||!navigator.onLine)return 0;const pending=await getPendingInvoices();if(!pending.length)return 0;const [sale,cash,last]=await Promise.all([getSaleDay(u.DefaultBranch),getCash(u.UserNo),getLastInvoice(u.DefaultBranch)]);let inv=Number(last.InvoiceNo)||0;let count=0;const remain:ReturnType<typeof buildInvoiceDraft>[]=[];for(const p of pending){try{const rebased=rebasePendingInvoice(p,{invoiceNo:String(inv+count),queue:Number(last.Queue)||0,cashNo:Number(cash.CashNo)||0,salesDate:dateOnly(sale.LineDate)});await insertInvoice(rebased);count++;}catch{remain.push(p);}}await setPendingInvoices(remain);return count;},[]);
 useEffect(()=>{ const on=()=>syncPending().catch(()=>{}); window.addEventListener('online',on); return()=>window.removeEventListener('online',on); },[syncPending]);
 const updatePrinterSettings=(v:LocalPrinterSettings)=>{setPrinterSettings(v);saveLocalSettings(v);};
 const value:PosCtx={...catalog,user,loading,error,cart,orderType:orderTypeState,discount,delivery,note,pendingOrders,printerSettings,addProduct,updateQty,removeItem,clearCart,setOrderType,setDiscount:setDiscountState,setDelivery,setNote,totals,refreshCatalog,holdOrder,restoreOrder,deleteOrder,checkout,syncPending,setPrinterSettings:updatePrinterSettings};
 return <C.Provider value={value}>{children}</C.Provider>;
}
export function usePos(){const v=useContext(C);if(!v)throw new Error('usePos must be inside PosProvider');return v;}
function sameIds<T extends object>(a:T[],b:T[],key:keyof T){return a.length===b.length&&a.every(x=>b.some(y=>y[key]===x[key]));}
function dateOnly(v:unknown){const d=new Date(String(v||''));return Number.isNaN(d.getTime())?new Date().toISOString().slice(0,10):`${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;}
